#!/usr/bin/env python3

import sys
import socket
import datetime
import json

MSG_SIZE = 1500
TIMEOUT = 30



'''
For Duplicate packets we have a dictionary that can be looked up.

DUPLICATE PACKET CONCERNS
1. I am not sure where to put the dictionary check. Put before I ack or before I read?
2. It doesnt even work lol, check the netsim and run it

I am a bit confused about what to do about out of order packets

Also, when I try to log(decoded['sequence']) I can't run the program and I have no clue why
'''

# A dictionary with a key of the SEQN and a value of the packet.
# Can be used for constant time lookup of duplicates
packets = {}

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")
  sys.stderr.flush()


def main():
  # Bind to localhost and an ephemeral port
  udp_ip = "127.0.0.1"
  udp_port = 0

  # Set up the socket
  sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
  sock.bind((udp_ip, udp_port))
  sock.settimeout(TIMEOUT)

  # Get port we bound to
  udp_port = sock.getsockname()[1]
  log(f"[bound] {udp_port}")

  # Now listen for packets
  while True:
    result = sock.recvfrom(MSG_SIZE)

    # If nothing is ready, we hit the timeout
    if result:
      (data, addr) = result
      data = data.decode('ascii')

      try:
        decoded = json.loads(data)

        # If the EOF flag is set, exit
        if decoded['eof']:
          log("[completed]")
          sys.exit(0)

        # If there is data, we accept it and print it out
        if decoded['data']:
          # If we receive data, we assume it's in-order
          # You will need to do much more here

          log(f"[recv data] {decoded['sequence']} ({len(decoded['data'])}) ACCEPTED (in-order)")
          sys.stdout.write(decoded['data'])


        # Send back an ack to the sender
        # Check the dictionary for duplicate packets
        if packets.get(decoded['sequence']) == None:
          log("Packet has never been here")
        #  log("SQN is: " + decoded[sequence])
          # If it has never been here before, add it to the list and ack it, otherwise drop it
          packets[decoded['sequence']] = decoded
          msg = json.dumps({"ack": decoded['sequence'] + len(decoded['data'])})
          log("ABOUT TO SEND " + msg)
          if sock.sendto(msg.encode('ascii'), addr) < len(msg):
            log("[error] unable to fully send packet")
        else:
          log("Packet has been here")

      except (ValueError, KeyError, TypeError) as exc:
        log("[recv corrupt packet]")
        raise exc
    else:
      log("[error] timeout")
      sys.exit(-1)

if __name__ == '__main__':
  main()
